printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
endOfLine: lf

overrides:
  - files: '*.json'
    options:
      tabWidth: 4
  - files:
      - package.json
      - public/manifest.json
      - generate-react-cli.json
    options:
      tabWidth: 2
